### ISSUE TITLE
关于AS_INT宏定义

### ISSUE THREAD

**Issue by tameshop** [BeeFramework/BeeFancy#1]
你好，我想问下，在NSObject+BeeProperty.h中定义了AS_INT宏，实现了和枚举类似的作用，为什么不直接用枚举？能否说说有什么特别的好处

**Comment by gavinkwoe** [comment]
1. AS_INT在.mm中定义，随版本编译后不可修改，而ENUM在头文件.h中定义，可以修改。
2. AS_INT必须定义在一个类中，引用方式是ClassName.PropertyName，这样语义更明确。

总结来讲，AS_INT解决了为一个INT数值起一个专属于某一类的有语义的名字的问题，并保证不可修改。

**Comment by tameshop** [comment]
ok，谢谢，期待你的更新
